version: "3.9"

services:
  postgres:
    image: postgis/postgis:latest
    platform: linux/amd64
    container_name: flare-test
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: tester
      POSTGRES_DB: flare_test
    ports:
      - "5434:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata_test:
