FROM node:20-slim

RUN npm install -g firebase-tools@latest

WORKDIR /srv/firebase

COPY firebase.json ./
COPY .firebaserc ./
COPY firestore.indexes.json ./
COPY firestore.rules ./
COPY storage.rules ./

VOLUME [ "/srv/firebase/localTest" ]

EXPOSE 8080 9099 9199 4000

CMD [ "sh", "-c", "firebase emulators:start" ]