import type { Metadata } from 'next';
import { Nunito, PT_Sans } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '@/components/context/AuthContext';
import { ServerUserProvider } from '@/components/context/ServerUserContext';
import { ToastContainer } from 'react-toastify';
import { getAuthenticatedAppForUser } from '@/lib/firebase/auth/configs/serverApp';
import { Analytics } from '@vercel/analytics/next';
import { SpeedInsights } from '@vercel/speed-insights/next';
import MainBanner from '@/components/banners/mainBanner/MainBanner';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css'; // Import the CSS
config.autoAddCss = false;


const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
  display: 'swap',
});

const pt_sans = PT_Sans({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  variable: '--font-pt_sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const { currentUser } = await getAuthenticatedAppForUser();


  const userData = currentUser
    ? {
        uid: currentUser.uid,
        email: currentUser.email,
        displayName: currentUser.displayName,
      }
    : null;

  return (
    <html lang="en">
      <body className={`${nunito.variable} ${pt_sans.variable} antialiased`}>
        <ServerUserProvider user={userData}>
          <AuthProvider>{children}</AuthProvider>
          <Analytics />
          <SpeedInsights />
          <ToastContainer position="bottom-right" />
        </ServerUserProvider>
      </body>
    </html>
  );
}
