import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito, PT_Sans } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/components/context/AuthContext";

import UserContext from "@/components/context/UserContext";
import { getAuthenticatedAppForUser } from "@/lib/firebase/auth/serverApp";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ['latin'],
  display: "swap"
})

const pt_sans = PT_Sans({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  variable: "--font-pt_sans",
  subsets: ["latin"]
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) 
{
  const {currentUser} = await getAuthenticatedAppForUser()

  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${pt_sans.variable} antialiased`}
      >
        <UserContext initialUser={currentUser?.toJSON()}>
          <AuthProvider>
            {children}
          </AuthProvider>
        </UserContext>
      </body>
    </html>
  );
}
