import type { Metadata } from 'next';
import { Nunito, PT_Sans } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '@/components/context/AuthContext';
import { ServerUserProvider } from '@/components/context/ServerUserContext';
import { ToastContainer } from 'react-toastify';
import PrimaryButton from '@/components/buttons/primaryButton/PrimaryButton';
import { signOutUser } from '@/lib/firebase/auth/signOutUser';
import { getAuthenticatedAppForUser } from '@/lib/firebase/auth/configs/serverApp';

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
  display: 'swap',
});

const pt_sans = PT_Sans({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  variable: '--font-pt_sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const { currentUser } = await getAuthenticatedAppForUser();

  

  const userData = currentUser
    ? {
        uid: currentUser.uid,
        email: currentUser.email,
        displayName: currentUser.displayName,
      }
    : null;

  return (
    <html lang="en">
      <body className={`${nunito.variable} ${pt_sans.variable} antialiased`}>
        <ServerUserProvider user={userData}>
          <AuthProvider><PrimaryButton click={signOutUser} text='signOut' size='medium'/>{children}<ToastContainer position='bottom-right'/></AuthProvider>
        </ServerUserProvider>
      </body>
    </html>
  );
}
